### ISSUE TITLE
Original Repository is Gone

### ISSUE THREAD

**Issue by KingGamingYT** [KingGamingYT/oldcord#1]
Hi so today without warning milbits privated his account and the original oldcord repository. No idea why. I'll update this issue if I find anything else out in the future.

Update: Milbits' account was temporarily shadowbanned by github automatically. He has since been un-shadowbanned, and I'm gonna revert the changes I made here since the original will work again.

**Comment by milbits** [comment]
my profile was private all the time but something with github broke for some reason...? like it just wont build a page
images (like the preview) all completely broke and i have no idea why

![image](https://github.com/user-attachments/assets/6ed3557f-5dee-4bdd-bc99-93a4357f1a7d)
![image](https://github.com/user-attachments/assets/d7cbc358-6dc4-4a76-8359-fa2f407c996c)

**Comment by damoyai** [comment]
looks like i got shadowbanned for some reason..?
i already sent a support ticket to gh but i didnt even get an email telling me, i just found out with a banner saying "your account is flagged" when i tried to contact support because pages werent working

**Comment by KingGamingYT** [comment]
> looks like i got shadowbanned for some reason..?
> 
> i already sent a support ticket to gh but i didnt even get an email telling me, i just found out with a banner saying "your account is flagged" when i tried to contact support because pages werent working 

This happened to another person I follow just two months ago and their account has yet to make it out of shadowbanned hell, probably the worst outcome ngl

guess we'll see

**Comment by KingGamingYT** [comment]
oh yeah I can't see commits to the repository on github itself but I *can* see them in github desktop, so that's helpful 
![image](https://github.com/user-attachments/assets/411adffc-807a-4b0c-8176-41706773da32)

**Comment by damoyai** [comment]
i can do nothing this SUCKS
![image](https://github.com/user-attachments/assets/fdf61132-acd8-4c89-989c-184b63f1772f)
most reliable microsoft product

i cant even delete my account, that HAS to be against the law

**Comment by damoyai** [comment]
https://github.com/oldcordtheme/OldCord
this will likely be a temporary repo, if my account gets unbanned i'll transfer the og repo to @oldcordtheme (which is gonna be oldcord but lowercase)
sorry for all this repo, username change, etc. bs but this website sucks lmao

**Comment by KingGamingYT** [comment]
> my profile was private all the time but something with github broke for some reason...? like it just wont build a page images (like the preview) all completely broke and i have no idea why
> 

hang on this messages appears for me now

**Comment by milbits** [comment]
fake news title
